// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOoyKJqLYu1Rl99RSRC41jY8EjqbA3Jhs',
    appId: '1:392433629443:web:3c0f8bfbc4ab90b9119136',
    messagingSenderId: '392433629443',
    projectId: 'foodie-5f7eb',
    authDomain: 'foodie-5f7eb.firebaseapp.com',
    storageBucket: 'foodie-5f7eb.appspot.com',
    measurementId: 'G-V72F7GWZCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd_g_MG2bvehUG0gWCCnx_WgGTR_5INxo',
    appId: '1:392433629443:android:0872914dbea8333d119136',
    messagingSenderId: '392433629443',
    projectId: 'foodie-5f7eb',
    storageBucket: 'foodie-5f7eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOvz8aR4o2OFiXpra5wUY1Z1N1RwJyz-Q',
    appId: '1:392433629443:ios:f731866d5b904321119136',
    messagingSenderId: '392433629443',
    projectId: 'foodie-5f7eb',
    storageBucket: 'foodie-5f7eb.appspot.com',
    iosBundleId: 'com.example.foodieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOvz8aR4o2OFiXpra5wUY1Z1N1RwJyz-Q',
    appId: '1:392433629443:ios:f34904e9a792cc89119136',
    messagingSenderId: '392433629443',
    projectId: 'foodie-5f7eb',
    storageBucket: 'foodie-5f7eb.appspot.com',
    iosBundleId: 'com.example.foodieApp.RunnerTests',
  );
}
